### ISSUE TITLE
关于底部栏图片的大小

### ISSUE THREAD

**Issue by wenchaosong** [chaychan/BottomBarLayout#1]
应该要添加设置图片的大小,并且整个容器最好有个 padding 

![default](https://user-images.githubusercontent.com/16938075/28853273-f862f740-7761-11e7-9d3b-9bb4f149feee.png)

可以看到没有 padding 会显得比较挤,而且图片稍微有点大

**Comment by chaychan** [comment]
@wenchaosong 兄弟，其实底部图标是处于居中的位置，文字在它的下方，你之所以出现这个问题是因为你的图标较大，建议你适当调小图标的宽高，这样图标一小就会有居中的效果，个人觉得并不需要设置padding,你可以看下demo的效果，图标是居中的，所以建议你缩小图标的宽高，放在xxhdpi文件夹的图标大小建议是96*96

**Comment by wenchaosong** [comment]
@chaychan 你说的也是可行的方法,我上面说的你可以看作是一个建议,但是好的第三方库不是要求别人怎么样,而是自己有相应的接口去处理相应的问题,不可能每个人都去切 96*96 的图标.其实我已经改了一下你的库,就多加了一个图标的属性,花了几分钟,不管图标多大,重新设置想要多大就多大,跟文字大小一样可以设置

**Comment by chaychan** [comment]
@wenchaosong 嗯嗯，你说得对，我会继续完善的
