### ISSUE TITLE
出现了两个标签都选中的状态

### ISSUE THREAD

**Issue by Thinkan** [chaychan/BottomBarLayout#11]
你好，看了你写的BottomBarLayout很赞，我发现了你的Demo中在第一个标签页还没有刷新完成的状态下点击其他标签页，虽然刷新动画停止了，但是经过3s过后，第一个标签还是会处于选中状态，此时，点击后三个标签，第一个标签的选中状态也还是不会取消。

**Comment by cwx2016** [comment]
您好，使用setCurrentItem方法选中页面，也出现了两个标签都选中的情况

**Comment by chaychan** [comment]
@Thinkan @cwx2016  已修复，多谢你们提出问题，已经发布新版本1.1.0
