### ISSUE TITLE
有没有方法关闭默认滑动切换fragment？

### ISSUE THREAD

**Issue by chenleicpp** [chaychan/BottomBarLayout#17]

**Comment by chaychan** [comment]
@chenleicpp  可以使用NoScrollViewPager即封装的不能滑动的ViewPager

/**
 * 自定义一个不能左右滑动的ViewPager
 * @author chaychan
 *
 */
public class NoScrollViewPager extends ViewPager {

	public NoScrollViewPager(Context context, AttributeSet attrs) {
		super(context, attrs);
	}

	public NoScrollViewPager(Context context) {
		super(context);
	}

	@Override
	public boolean onTouchEvent(MotionEvent arg0) {
		return false;
	}
	
	/**
	 * 不拦截事件
	 */
	@Override
	public boolean onInterceptTouchEvent(MotionEvent arg0) {
		return false;
	}

	@Override
	public boolean dispatchTouchEvent(MotionEvent ev) {
		return super.dispatchTouchEvent(ev);
	}
}
