### ISSUE TITLE
个人意见:关于监听的问题：

### ISSUE THREAD

**Issue by LLQQHH** [chaychan/BottomBarLayout#19]
mBottomBar.setOnTabSelectedListener(new BottomBar.OnTabSelectedListener()
 {
            @Override
            public void onTabSelected(int position, int prePosition) {
                //选中
            }
            @Override
            public void onTabUnselected(int position) {
             //未选中
            }
            @Override
            public void onTabReselected(int position) {
                //重复选中
            }
        });
个人认为监听方式改为这样是最好的，希望采纳

**Comment by chaychan** [comment]
@LLQQHH 感觉没必要加多未选中和重复选中的回调，除了选中的position外，其他的就是未选中的了，判断position和prePosition是否一致就知道是否是重复选中了

**Comment by LLQQHH** [comment]
好吧，我只是认为一个方法一个职责，你在一个方法里面就要负责重复选，已选，重复选，这样不是很好，现在比较好的框架都是这么做的！
