### ISSUE TITLE
滑动切换问题

### ISSUE THREAD

**Issue by Niekevin007** [chaychan/BottomBarLayout#21]
smoothScroll 设置false 、    mBottomBarLayout.setSmoothScroll(false); 都无法禁止掉项目的fragment 左右滑动切换

**Comment by chaychan** [comment]
@Niekevin007 mBottomBarLayout.setSmoothScroll(false)并不是禁止fragment左右滑动的，指的是是否关闭滑动动画，如果要禁止左右滑动，可以使用不左右滑动的ViewPager

**Comment by is1988** [comment]
mBottomBarLayout.setSmoothScroll(false); 只是关闭点击后的滑动动画，如果你需要禁止viewpager滑动需要重写viewpager。
