### ISSUE TITLE
导航图标修改默认选择项

### ISSUE THREAD

**Issue by zhenghow** [chaychan/BottomBarLayout#27]
有没有修改默认选择底部导航图标的方法，比如打开后默认展示的是第三个fragment，相应的导航图标也应该是选中第三个

**Comment by chaychan** [comment]
@zhenghow 有的，你在设置完adapter以后调用mBottomBarLayout.setCurrentItem(2); 就可以了

**Comment by zhenghow** [comment]
谢谢

**Comment by chaychan** [comment]
@zhenghow 不客气
