### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by CheneyHen** [chaychan/BottomBarLayout#29]
项目确实不错，这样一来底部导航可以很方便的实现，使用过程发现一点小建议，给一下，同时也方便大家了。
1.依赖。作者写的貌似有点问题，建议还是用 implementation关键字或者api关键字吧，而不是compile 
2.最小sdk。这个包有最小SDK要求minSdk的版本必须是16.
3.当然了，能写出这样的项目还是不错的，继续努力！

**Comment by fg2q1q3q** [comment]
三条全是废话

**Comment by CheneyHen** [comment]
废话，这么俏丽吗😂

**Comment by chaychan** [comment]
@CheneyHen 你是要求更改最低版本么，16已经很低了，现在市面上基本都是18以上的系统
