### ISSUE TITLE
首页放了四个fragment，在二级界面，添加一个按钮，跳转首页的任意一个fragment，有跳转方法吗

### ISSUE THREAD

**Issue by 86userused** [chaychan/BottomBarLayout#35]

**Comment by chaychan** [comment]
你的意思是Afragment要跳转到随意一个fragment比如Cfragment吗？

**Comment by 86userused** [comment]
@chaychan MainActivity内有 4个fragment， 点击按钮，跳转任意一个的fragment

**Comment by chaychan** [comment]
可以的 直接调用BottomBarLayout的setCurrentItem(position)方法跳转

**Comment by 86userused** [comment]
thanks
