### ISSUE TITLE
可以支持后台配置菜单数据么？

### ISSUE THREAD

**Issue by luck-fc** [chaychan/BottomBarLayout#38]

**Comment by chaychan** [comment]
@luck-fc Tab支持动态添加的 如果你要后台配置菜单数据 那么只要请求到后台返回的数据后处理一下就可以了

**Comment by luck-fc** [comment]
好像不支持图片从网络获取的

**Comment by chaychan** [comment]
@luck-fc BottomBarLayout都可以直接获取到对应tab的ImageView了，你如果使用Glide或者ImageLoader这种支持加载网络图片的框架，有ImageView和url，就可以展示了

**Comment by luck-fc** [comment]
好吧！🙏
