### ISSUE TITLE
无法左右滑动，点击切换的时候也没有动画效果

### ISSUE THREAD

**Issue by EpicWang** [chaychan/BottomBarLayout#39]
版本：1.2.1
集成方式：module
minSdkVersion：16
compileSdkVersion：28
buildToolsVersion："28.0.3"
gradle：3.4.1

问题描述：设置了mBottomBarLayout.setSmoothScroll(true)，并且在xml中也设置了app:smoothScroll="true"，tab无法使用滑动的方式切换，也没有gif中的动画效果

**Comment by chaychan** [comment]
这个要搭配viewPager的才行的哦，请确保你是使用viewPager的方式
