### ISSUE TITLE
怎么动态切换按钮

### ISSUE THREAD

**Issue by Albertbottle** [chaychan/BottomBarLayout#47]
大佬，底部导航默认选中第一个按钮，当我点击其他按钮时跳出一个activity登录页面，当登录成功关闭登录页面后显示的是我点击后的页面，我想让登录后再重新回到默认第一页面按钮状态也是第一个选中，现在的问题是我只能设置页面显示第一个，底部导航按钮还是显示选中的其他按钮，而不是第一个按钮BottomBarItem hombottomItem = mBottomBarLayout.getBottomItem(0);
                        hombottomItem.setSelectedIcon(R.mipmap.home_select);   设置第一个按钮的状态也没用

**Comment by chaychan** [comment]
@Albertbottle 有对应设置选中的api, 你可以调用mBottomBarLayout.setCurrentItem(position)
