### ISSUE TITLE
因为加了LottieAnimationView导致无法预览

### ISSUE THREAD

**Issue by LLQQHH** [chaychan/BottomBarLayout#50]
java.lang.ClassNotFoundException: com.airbnb.lottie.LottieAnimationView

**Comment by chaychan** [comment]
@LLQQHH 这边试了lottie的依赖拉取是正常的，请检测下电脑的网络环境或者重新rebuild下，或使用AS的Invalidate Caches/Restart
![image](https://user-images.githubusercontent.com/16892788/119635243-138e1980-be46-11eb-8644-a5e9ea944266.png)

**Comment by LLQQHH** [comment]
试了一下，但是包另外一个错
![image](https://user-images.githubusercontent.com/19651932/119635781-9616d900-be46-11eb-800f-54fc7de1c620.png)

**Comment by chaychan** [comment]
@LLQQHH 这边克隆了最新代码跑起来并没有这个问题，你可以看下那些xml中是不是不小心改到了，BottomBarLayout包裹下的item如果不是BottomBarItem就会报这个错的
