### ISSUE TITLE
如何实现中间的突出于导航栏

### ISSUE THREAD

**Issue by LLQQHH** [chaychan/BottomBarLayout#51]
类似这样的效果
![image](https://user-images.githubusercontent.com/19651932/122852314-fe23e680-d342-11eb-9285-fa2b90b2252e.png)
建议添加类似tabLayout的功能，支持添加自定义View，BottomBarItem.setCustomView(View view)

**Comment by chaychan** [comment]
@LLQQHH 最新版已支持
