### ISSUE TITLE
DynamicAddItemActivity 类里面设置颜色不生效

### ISSUE THREAD

**Issue by likaiha** [chaychan/BottomBarLayout#58]
private BottomBarItem createBottomBarItem(int i) {
        BottomBarItem item = new BottomBarItem.Builder(this)
                .titleTextBold(true)
                .titleTextSize(UIUtils.dip2Px(this, 8))
                .titleNormalColor(R.color.tab_normal_color)
                .titleSelectedColor(R.color.tab_selected_color)
                .marginTop(UIUtils.dip2Px(this, -5))
     
                .create(mNormalIconIds[i], mSelectedIconIds[i], getString(mTitleIds[i]));
        return item;
    }

类里面和xml里都有颜色设置  但是未生效   @chaychan

**Comment by chaychan** [comment]
@likaiha 演示代码有误
`
.titleNormalColor(R.color.tab_normal_color)
.titleSelectedColor(R.color.tab_selected_color)`
应为：
`.titleNormalColor(geResources().getColor(R.color.tab_normal_color))
.titleSelectedColor(geResources().getColor(R.color.tab_selected_color))`
