### ISSUE TITLE
关于扩展

### ISSUE THREAD

**Issue by huyanminggithub** [chaychan/BottomBarLayout#7]
作者您好，首先，非常感谢您的付出并开源了这个轻量级的控件。我下载了源码，仔细的查看过，并结合业务需求提几点意见。
1.首先，BottomLayout 和BottomItem都是继承自线性布局，同时目前只支持xml方式配置使用，这里有一个问题，如果我需要将一个Activity进行封装，动态配置fragment,和底部按钮，就无法实现。
2.现在的使用方式，是必须强行调用setViewPager方法，也就是说，此空间跟viewpager有很强的耦合性。
那么，如果我的需求是，不需要使用viewpager 想通过hideshow的方式 使用，这个控件又不允许了。
3.针对点击回调，应该抽象出onItemReSelected()方法，单独处理，二不要在onItemSelected里边通过currentitem和position是否相等来做判断，
针对以上3个问题我已经修改了代码。欢迎交流

**Comment by chaychan** [comment]
@huyanminggithub 看下你的修改

**Comment by LLQQHH** [comment]
@huyanminggithub  可否把您的改完之后的源码分享一下！
