### ISSUE TITLE
依赖失败

### ISSUE THREAD

**Issue by lxhtiamo** [chaychan/BottomBarLayout#9]
Error:(42, 13) Failed to resolve: com.github.chaychan:BottomBarLayout:1.0.9
<a href="openFile:C:/Users/Administrator/Desktop/kj/LinewellFramework/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by chaychan** [comment]
@lxhtiamo 你有在根目录的gradle添加jitpack的仓库地址吗

**Comment by lxhtiamo** [comment]
谢谢提醒!

**Comment by chaychan** [comment]
不客气

**Comment by chaychan** [comment]
@lxhtiamo 不客气

**Comment by lxhtiamo** [comment]
我在使用的时候发现如果fragment里面的textview文字使用默认的颜色就是不设置颜色,在首页fragment多次切换后 字体颜色逐渐加深最后变成黑色
